### ISSUE TITLE
Confusing Inkscape extension

### ISSUE THREAD

**Issue by mathlusiverse** [xyz2tex/svg2tikz#121]
**Describe the bug**
I followed the official instruction on manually installing the extension.  https://inkscape.org/develop/extensions/
To manually install a new extension, download and unpack the archive file. Copy the files into the directory listed at Setting > Preferences > System: User extensions. After a restart of Inkscape, the new extension will be available.

After I restart Inkscape, and open the Inkscape Extension Manager, it said the extension is an Orphan Extensions version 0. And then the following message also appear:

```
<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()

(manage_extensions.py:95856): Gtk-WARNING **: 14:24:31.986: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:24:31.987: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:24:31.987: Error loading theme icon 'dialog-warning' for stock: Icon 'dialog-warning' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:24:32.043: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita
Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/main.py", line 232, in local_information
    self.load_window("info", pixmaps=self.pixmaps, item=self.local.selected)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/window.py", line 110, in load_window
    return self.gapp.load_window(name, *args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 134, in load_window
    window = self.proto_window(name)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 152, in proto_window
    window = self._initial[name](self)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 76, in __init__
    self.inx = ExtensionTreeView(self.widget("inx"), selected=self.select_inx)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 37, in __init__
    super().__init__(*args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/listview.py", line 81, in __init__
    self.setup()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 42, in setup
    self.ViewColumn("Name", expand=True, text="name")
AttributeError: 'ExtensionTreeView' object has no attribute 'ViewColumn'
Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/main.py", line 232, in local_information
    self.load_window("info", pixmaps=self.pixmaps, item=self.local.selected)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/window.py", line 110, in load_window
    return self.gapp.load_window(name, *args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 134, in load_window
    window = self.proto_window(name)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 152, in proto_window
    window = self._initial[name](self)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 76, in __init__
    self.inx = ExtensionTreeView(self.widget("inx"), selected=self.select_inx)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 37, in __init__
    super().__init__(*args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/listview.py", line 81, in __init__
    self.setup()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 42, in setup
    self.ViewColumn("Name", expand=True, text="name")
AttributeError: 'ExtensionTreeView' object has no attribute 'ViewColumn'
Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/main.py", line 232, in local_information
    self.load_window("info", pixmaps=self.pixmaps, item=self.local.selected)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/window.py", line 110, in load_window
    return self.gapp.load_window(name, *args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 134, in load_window
    window = self.proto_window(name)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 152, in proto_window
    window = self._initial[name](self)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 76, in __init__
    self.inx = ExtensionTreeView(self.widget("inx"), selected=self.select_inx)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 37, in __init__
    super().__init__(*args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/listview.py", line 81, in __init__
    self.setup()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 42, in setup
    self.ViewColumn("Name", expand=True, text="name")
AttributeError: 'ExtensionTreeView' object has no attribute 'ViewColumn'
Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/main.py", line 232, in local_information
    self.load_window("info", pixmaps=self.pixmaps, item=self.local.selected)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/window.py", line 110, in load_window
    return self.gapp.load_window(name, *args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 134, in load_window
    window = self.proto_window(name)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 152, in proto_window
    window = self._initial[name](self)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 76, in __init__
    self.inx = ExtensionTreeView(self.widget("inx"), selected=self.select_inx)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 37, in __init__
    super().__init__(*args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/listview.py", line 81, in __init__
    self.setup()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 42, in setup
    self.ViewColumn("Name", expand=True, text="name")
AttributeError: 'ExtensionTreeView' object has no attribute 'ViewColumn'
Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/main.py", line 232, in local_information
    self.load_window("info", pixmaps=self.pixmaps, item=self.local.selected)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/window.py", line 110, in load_window
    return self.gapp.load_window(name, *args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 134, in load_window
    window = self.proto_window(name)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/app.py", line 152, in proto_window
    window = self._initial[name](self)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 76, in __init__
    self.inx = ExtensionTreeView(self.widget("inx"), selected=self.select_inx)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 37, in __init__
    super().__init__(*args, **kwargs)
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/listview.py", line 81, in __init__
    self.setup()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/inkman/gui/info.py", line 42, in setup
    self.ViewColumn("Name", expand=True, text="name")
AttributeError: 'ExtensionTreeView' object has no attribute 'ViewColumn'

(manage_extensions.py:95856): Gtk-WARNING **: 14:24:43.556: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:24:43.597: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:24:43.619: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:24:43.875: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.225: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.241: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.260: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.278: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.297: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.314: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.332: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.350: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.368: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

(manage_extensions.py:95856): Gtk-WARNING **: 14:29:43.386: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita
```

**Setup:**
 - Mode: inkscape
 - SVG2TikZ version: [latest on GitHub  as of 2023-May-27]
 - Mac OS Ventura 13.3.1
 - Inkscape version:  1.2.1
 
**To Reproduce**
 - Manual installation of Svg2TikZ
 - Output result
 - Options

**Expected behavior**
I delete everything from the extension folder and try again a few times. I decided to test the extension on a a very simple SVG file anyway. It seems working. But the error message is really confusing, and give the impression that the extension is broken.

**Additional context**
It will be nice to:
-  clean up the code so no error message will show up
-  does not say Orphan Extensions version 0.
-  submit Svg2TikZ as an Inkscape official extension, so user can install directly from within Inkscape's own Extension Manager, with minimal effort from the user; and also will give confidence of Inkscape user that the extension is well-maintained and updated.

**Comment by ldevillez** [comment]
Hello @mathlusiverse,

Thanks for the issue. From all the error message, I feel like the error come directly from inkex (the extension module of inkscape). Did you try to wipe (if possible) all your inkscape installation ? (removing the package but also the config). Another possibility could also to reset the config (It is possible to do it from the inkscape gui).

Normally there should be no error message from the extension (That is also why I think there might be a problem with your installation.

And yes the next big step for the project is to be directly included in inkscape official extension :)
