### ISSUE TITLE
`svg2tikz` Error

### ISSUE THREAD

**Issue by FelipeWcosta** [xyz2tex/svg2tikz#122]
Hello everyone!

I followed all the steps in the documentation to install the `svg2tikz` Inkscape extension but when a try to execute the extension this erro appears to me:
```
Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1855, in <module>
    main_inkscape()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1838, in main_inkscape
    effect.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1766, in save_raw
    with codecs.open(self.options.output, "w", "utf8") as file:
  File "C:\Program Files\Inkscape\lib\python3.10\codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Inkscape\\share\\inkscape\\extensions\\IA'
```

I think that must be the user permission denied, so how can I fix it?

**Comment by ldevillez** [comment]
Hello @FelipeWcosta,

What is the version of Inkscape and SVG2Tikz that you are using ?

Also is it when you try to save a file (with the extension) ?
Could you try by checking the copy to clipboard box ?

**Comment by FelipeWcosta** [comment]
Hi @ldevillez, sorry for taking so long.

So, for Inkscape and SVG2Tikz I am using the latest version available for boths. This happened when I try to save in the same directory where is the extension files, when I use the "save file" don't occour any erro and I can copy to clipboard without erros.

I think that could be the adiministrator permissions.

**Comment by ldevillez** [comment]
Hello @FelipeWcosta,

Yes I think the same :) Then closing this issue
