### ISSUE TITLE
In parse_style: TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by ariel-co** [xyz2tex/svg2tikz#48]
Similar to #37:

```
Traceback (most recent call last):
  File "tikz_export.py", line 1478, in <module>
    main_inkscape()
  File "tikz_export.py", line 1462, in main_inkscape
    effect.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "tikz_export.py", line 1363, in effect
    s = self._output_group(nodes, graphics_state)
  File "tikz_export.py", line 1333, in _output_group
    s += self._handle_group(node, graphics_state, accumulated_state)
  File "tikz_export.py", line 994, in _handle_group
    code = self._output_group(groupnode, accumulated_state.accumulate(graphics_state))
  File "tikz_export.py", line 1310, in _output_group
    graphics_state = GraphicsState(node)
  File "tikz_export.py", line 531, in __init__
    self._get_graphics_state(svg_node)
  File "tikz_export.py", line 537, in _get_graphics_state
    style = parse_style(node.get('style', ''))
  File "tikz_export.py", line 508, in parse_style
    return dict([list(map(str.strip, i.split(":"))) for i in s.split(";") if len(i)])
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

parse_style receives a unicode string and maps the output of split (also unicode strings) explicitly through str.split.

The fix is simple enough:

```
--- tikz_export.orig.py 2020-04-06 00:08:11.993088800 -0400
+++ tikz_export.py      2020-04-06 00:05:31.422466100 -0400
@@ -505,7 +505,7 @@
     """Create a dictionary from the value of an inline style attribute"""
     # This version strips leading and trailing whitespace from keys and values
     if s:
-        return dict([list(map(str.strip, i.split(":"))) for i in s.split(";") if len(i)])
+        return dict( (_.strip() for _ in kv.split(':')) for kv in (_.strip() for _ in s.split(';')) if len(kv) )
     else:
         return {}
```

(I added one strip() because `"color: blue;  ; fill: red;"` is valid CSS.)

**Comment by jiagengliu** [comment]
Same problem, and the solution works. Thanks!

**Comment by ldevillez** [comment]
Thanks @ariel-co :)
