### ISSUE TITLE
failed test, help ?

### ISSUE THREAD

**Issue by elvyre** [xyz2tex/svg2tikz#65]
I try to use svg2tex as an inkscape extension or a command line tool, but both do not work for me. Below are the results of test. Thank you for your help :-)

python test_svgtestsuite.py 
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK

python test_svg2tikz.py 
EEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_no_svgheight_error (__main__.BugsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 139, in test_no_svgheight_error
    code = convert_svg(no_height_svg)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_no_used_defs (__main__.DefsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 175, in test_no_used_defs
    code = convert_svg(defs1_svg)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_basic_codeonly (__main__.InterfaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 45, in test_basic_codeonly
    code = convert_svg(basic_svg, codeoutput="codeonly")
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_basic_figonly (__main__.InterfaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 50, in test_basic_figonly
    code = convert_svg(basic_svg, codeoutput="figonly")
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_basicsvg (__main__.InterfaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 41, in test_basicsvg
    code = convert_svg(basic_svg)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_no_ids (__main__.InterfaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 55, in test_no_ids
    code = convert_svg(basic2_svg, ids=[], verbose=True)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_select_id_rect1 (__main__.InterfaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 60, in test_select_id_rect1
    code = convert_svg(basic2_svg, ids=['rect1'], verbose=True)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_select_id_rect1and3 (__main__.InterfaceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 65, in test_select_id_rect1and3
    code = convert_svg(basic2_svg, ids=['rect1', 'rect3'], verbose=True)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_marker2_options (__main__.MarkersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 206, in test_marker2_options
    code = convert_svg(arrows_svg, markers="arrows", codeoutput="codeonly")
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_marker_options (__main__.MarkersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 202, in test_marker_options
    code = convert_svg(arrows_svg, markers="ignore", codeoutput="codeonly")
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_inherited_fill (__main__.PaintingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 87, in test_inherited_fill
    code = convert_svg(paint_svg)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_px_in_output (__main__.TestIssue20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 236, in test_px_in_output
    code = convert_svg(self.test_svg2, codeoutput="codeonly")
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_pxtransform (__main__.TestIssue20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 231, in test_pxtransform
    code = convert_svg(self.test_svg)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_escape (__main__.TestTextMode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 114, in test_escape
    code = convert_svg(text_svg, codeoutput="codeonly")
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_math (__main__.TestTextMode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 124, in test_math
    code = convert_svg(text_svg, codeoutput="codeonly", texmode='math')
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_raw (__main__.TestTextMode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 120, in test_raw
    code = convert_svg(text_svg, codeoutput="codeonly", texmode='raw')
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 1455, in convert_svg
    effect = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

======================================================================
ERROR: test_exponential_notation_bug (__main__.TestTransformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_svg2tikz.py", line 93, in test_exponential_notation_bug
    converter = TikZPathExporter(inkscape_mode=False)
  File "/home/gatien/anaconda3/envs/phys/lib/python3.7/site-packages/svg2tikz/extensions/tikz_export.py", line 630, in __init__
    self.svg.unittouu = inkex.unittouu
AttributeError: 'TikZPathExporter' object has no attribute 'svg'

----------------------------------------------------------------------
Ran 17 tests in 0.004s

FAILED (errors=17)

**Comment by bcegkmqs23** [comment]
failed with same issue too

**Comment by bcegkmqs23** [comment]
I switched to another svg2tikz project which is an Inkscape plugin.

**Comment by ldevillez** [comment]
It should now be fixed, thanks :)
